### ISSUE TITLE
Content-Range is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by legas7** [kaltura/chunked-file-upload-jquery#1]
Hi!
I am constantly getting error related to CORS headers:
`XMLHttpRequest cannot load https://www.kaltura.com/api_v3/?(...). Request header field Content-Range is not allowed by Access-Control-Allow-Headers in preflight response.`

Here is my preflight OPTIONS request:
```HTTP 
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
Access-Control-Request-Headers:content-disposition, content-range
Access-Control-Request-Method:POST
Connection:keep-alive
Host:www.kaltura.com
Origin:http://localhost:50053
Referer:http://localhost:50053/Resources/Create
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

and response:
```HTTP
Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept, Range, Cache-Control
Access-Control-Allow-Methods:POST, GET, HEAD, OPTIONS
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:Server, Content-Length, Content-Range, Date
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:20
Content-Type:text/html
Date:Wed, 15 Mar 2017 13:33:21 GMT
Keep-Alive:timeout=5, max=100
Server:Apache
Vary:Accept-Encoding
X-Me:ny-front-api39
```

There is `Content-Range header` in `Access-Control-Expose-Headers` so why my browser stops me from POSTing next XHR's?

I am running this simple js code:
```javascript
    function InjectKalturaFileUploadNEW() {
        $('input[name="fileData"]').fileupload({
            apiURL: 'https://www.kaltura.com/api_v3/',
            url: 'https://www.kaltura.com/api_v3/?service=uploadToken&action=upload&format=1',
            ks: kalturaSession,
            singleFileUploads: true,
            dataType: 'json',
            autoUpload: true,
            maxChunkSize: 400000,
            submit: function (e, data) {
                console.log('submit fired')
            },
            done: function (e, data) {
                console.log('done fired')
            },

        }).on('fileuploaddone', function (e, data) {
            console.log('fileuploaddone fired.')
        }).on('fileuploadchunkdone', function (e, data) {
            console.log('chunkdone fired.')
        });
    }
```

Thanks!

**Comment by kaltura-hooks** [comment]
Hi @legas7,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hi @legas7,

I am confused about that too since like you said yourself, the response from Kaltura does have:
```
Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept, Range, Cache-Control
Access-Control-Allow-Methods:POST, GET, HEAD, OPTIONS
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:Server, Content-Length, Content-Range, Date
```
So the 'Range' in Access-Control-Allow-Headers means that the server agrees to accept range requests, then the response is Content-Range, which is included in Access-Control-Expose-Headers.

Can you please provide the repo with your full source code and, if possible, a public URL where you've placed it so I can debug it further?

**Comment by legas7** [comment]
I did further investigation, debugged my code under firefox, and found out that it is not the `content-range`  header that causes problem but `content-disposition` header present in `Access-Control-Request-Headers: content-disposition, content-range` which obviously is not accepted by server. 

Now if only I could eliminate `content-disposition` header from `OPTIONS` request I assume everything would work fine. When running bare code from this repo, `OPTIONS` request looks like this:
```HTTP
OPTIONS /api_v3/?service=uploadToken&action=upload&format=1&kalsig=(...) HTTP/1.1
Host: www.kaltura.com
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: null
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Access-Control-Request-Headers:
Accept: */*
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
```
But from within my application:
```HTTP
OPTIONS 
/api_v3/?service=uploadToken&action=upload&format=1&kalsig=(...) HTTP/1.1
Host: www.kaltura.com
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:50053
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Access-Control-Request-Headers: content-disposition, content-range
Accept: */*
Referer: http://localhost:50053/Resources/Create
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4
```

**Comment by jessp01** [comment]
Hi @legas7,

The Content-Disposition response-header field has been proposed as a means for the origin server to suggest a default filename if the user requests that the content is saved to a file. This usage is derived from the definition of Content-Disposition in RFC 1806.
Since in our case we're not saving anything on the user's disk but rather the opposite, I don't see why this should be needed.
Can you change js/jquery.fileupload.js:
```
ignoreChunkHeader: false,
```
to:
```
ignoreChunkHeader: true,
```
?

**Comment by legas7** [comment]
I ran across this solution virtually at the same moment.
Indeed it fixed the problem : )
Thank You very much!

**Comment by jessp01** [comment]
Most welcome. I've also made that change in the repo so others won't experience the issue. Thanks for reporting it.
